name: Test documentation

on:
  pull_request:
    branches:
      - master

jobs:
  buildcheck:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup .NET Core SDKs
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Install SHFB
        uses: Bassman2/setup-SHFB@main
        with:
          version: 2022.8.14.1
      - name: Build project
        run: dotnet build -c Release
      - name: Build documentation
        working-directory: Doc
        run: dotnet build -c Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: Doc/Help
