name: Test documentation

on:
  pull_request:
    branches:
      - master

jobs:
  buildcheck:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Install SHFB
        uses: Bassman2/setup-SHFB@9539b643a5f65125efa9365ab573bb75cdfd93fd
        with:
          version: '2022.8.14.1'
      - name: Build documentation
        working-directory: Doc
        run: dotnet build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: Doc/Help
