name: Test documentation

on:
  pull_request:
    branches:
      - master

jobs:
  buildcheck:
    runs-on: windows-2019
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup .NET Core SDKs
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install SHFB
        uses: Bassman2/setup-SHFB@v1
        with:
          version: '2022.8.14.1'
      - name: Build documentation
        working-directory: Doc
        run: dotnet build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: Doc/Help
